### ISSUE TITLE
when i composer install i found it 

### ISSUE THREAD

**Issue by mostafa300** [LaravelDaily/Laravel-Real-Estate-Venue-Portal#1]
![issue](https://user-images.githubusercontent.com/29531212/67954625-ef327280-fbf9-11e9-8e2f-3cc5e4b0dc8f.PNG)
 also i intall imagicak but still

**Comment by PovilasKorop** [comment]
@mostafa300 yes unfortunately Spatie Medialibrary requires Imagick. And you probably didn't install or configure it correctly if you're still getting this message.

Please refer to imagick installation and configuration docs.

**Comment by mostafa300** [comment]
yes .. i try alot but the best source to configuration is 
https://www.youtube.com/watch?v=qZ9_rq6c9uY 
thanks alot
