### ISSUE TITLE
Stuck setup !

### ISSUE THREAD

**Issue by thanhlamle** [LaravelDaily/Laravel-Real-Estate-Venue-Portal#3]
I have problem setup at this step, 
can you tell me how can i fix it .
Thanks so much.
![Stuck setup](https://user-images.githubusercontent.com/54069535/78424658-389b5800-7699-11ea-904f-ce6b85fc44ec.png)

**Comment by PovilasKorop** [comment]
@thanhlamle not sure, no one reported any bug like this, searched in the project, `globalLocations` variable is set globally: https://github.com/LaravelDaily/Laravel-Real-Estate-Venue-Portal/search?q=globallocations&unscoped_q=globallocations

**Comment by thanhlamle** [comment]
Sorry !
This is not bug, this is my mistake at AppServiceProvider.php
I have fix it 
Thanks so much.
