### ISSUE TITLE
Cann't load images using --seed 

### ISSUE THREAD

**Issue by Mohsing511** [LaravelDaily/Laravel-Real-Estate-Venue-Portal#5]
images URL is   
 http://localhost/storage/1/london.jpg

**Comment by PovilasKorop** [comment]
@Mohsing511 have you run `php artisan storage:link`?

**Comment by Mohsing511** [comment]
yes i have

**Comment by PovilasKorop** [comment]
@Mohsing511 then check your URLs, what domain name have you configured? Maybe it shouldn't be `http://localhost`? 
Maybe this article will help: https://quickadminpanel.com/blog/why-its-important-to-change-app_url-in-laravel-env-file/

**Comment by Mohsing511** [comment]
inside .env file
APP_URL=/laravel-Real-Estate-Venue-Portal-master/public
it works fine Thanks a lots Sir
This comment is for those who will gona face this issue

**Comment by Mohsing511** [comment]
Question came in my mind
for production purpose what will be the APP_URL???
